const EXERCISES_LIBRARY = [
  // ── Pecho ────────────────────────────────────────────────────────────────
  { id: "c01", name: "Press de banca con barra",          muscle: "Pecho",           equipment: "Barra",         compound: true  },
  { id: "c02", name: "Press de banca con mancuernas",     muscle: "Pecho",           equipment: "Mancuernas",    compound: true  },
  { id: "c03", name: "Press inclinado con mancuernas",    muscle: "Pecho",           equipment: "Mancuernas",    compound: true  },
  { id: "c04", name: "Press declinado con mancuernas",    muscle: "Pecho",           equipment: "Mancuernas",    compound: true  },
  { id: "c05", name: "Aperturas (Flyes) con mancuernas",  muscle: "Pecho",           equipment: "Mancuernas",    compound: false },
  { id: "c06", name: "Pec Deck / Contractora",            muscle: "Pecho",           equipment: "Máquina",       compound: false },
  { id: "c07", name: "Cruces en polea",                   muscle: "Pecho",           equipment: "Polea",         compound: false },
  { id: "c08", name: "Fondos en paralelas (Dips)",        muscle: "Pecho",           equipment: "Peso corporal", compound: true  },
  { id: "c09", name: "Press de pecho en máquina",         muscle: "Pecho",           equipment: "Máquina",       compound: true  },
  // ── Espalda ──────────────────────────────────────────────────────────────
  { id: "b01", name: "Dominadas (Pull-ups)",              muscle: "Espalda",         equipment: "Peso corporal", compound: true  },
  { id: "b02", name: "Jalón al pecho (agarre prono)",     muscle: "Espalda",         equipment: "Polea",         compound: true  },
  { id: "b03", name: "Jalón al pecho (agarre neutro)",    muscle: "Espalda",         equipment: "Polea",         compound: true  },
  { id: "b04", name: "Remo con barra",                    muscle: "Espalda",         equipment: "Barra",         compound: true  },
  { id: "b05", name: "Remo con mancuerna (unilateral)",   muscle: "Espalda",         equipment: "Mancuernas",    compound: true  },
  { id: "b06", name: "Remo en máquina",                   muscle: "Espalda",         equipment: "Máquina",       compound: true  },
  { id: "b07", name: "Remo en polea baja",                muscle: "Espalda",         equipment: "Polea",         compound: true  },
  { id: "b08", name: "Face pulls en polea",               muscle: "Espalda",         equipment: "Polea",         compound: false },
  { id: "b09", name: "Pull-over con mancuerna",           muscle: "Espalda",         equipment: "Mancuernas",    compound: false },
  { id: "b10", name: "Encogimientos (Shrugs)",            muscle: "Trapecios",       equipment: "Mancuernas",    compound: false },
  // ── Hombros ───────────────────────────────────────────────────────────────
  { id: "s01", name: "Press militar con barra",           muscle: "Hombros",         equipment: "Barra",         compound: true  },
  { id: "s02", name: "Press militar con mancuernas",      muscle: "Hombros",         equipment: "Mancuernas",    compound: true  },
  { id: "s03", name: "Elevaciones laterales",             muscle: "Hombros",         equipment: "Mancuernas",    compound: false },
  { id: "s04", name: "Elevaciones frontales",             muscle: "Hombros",         equipment: "Mancuernas",    compound: false },
  { id: "s05", name: "Pájaro / Reverse Fly",              muscle: "Hombros",         equipment: "Mancuernas",    compound: false },
  { id: "s06", name: "Press Arnold",                      muscle: "Hombros",         equipment: "Mancuernas",    compound: true  },
  { id: "s07", name: "Elevaciones laterales en polea",    muscle: "Hombros",         equipment: "Polea",         compound: false },
  // ── Bíceps ────────────────────────────────────────────────────────────────
  { id: "bi01", name: "Curl de bíceps con barra",         muscle: "Bíceps",          equipment: "Barra",         compound: false },
  { id: "bi02", name: "Curl de bíceps con mancuernas",    muscle: "Bíceps",          equipment: "Mancuernas",    compound: false },
  { id: "bi03", name: "Curl martillo con mancuernas",     muscle: "Bíceps",          equipment: "Mancuernas",    compound: false },
  { id: "bi04", name: "Curl en polea baja",               muscle: "Bíceps",          equipment: "Polea",         compound: false },
  { id: "bi05", name: "Curl concentrado",                 muscle: "Bíceps",          equipment: "Mancuernas",    compound: false },
  { id: "bi06", name: "Curl predicador (Scott)",          muscle: "Bíceps",          equipment: "Barra",         compound: false },
  // ── Tríceps ───────────────────────────────────────────────────────────────
  { id: "t01", name: "Extensión en polea (cuerda)",       muscle: "Tríceps",         equipment: "Polea",         compound: false },
  { id: "t02", name: "Extensión en polea (barra recta)",  muscle: "Tríceps",         equipment: "Polea",         compound: false },
  { id: "t03", name: "Press francés con barra",           muscle: "Tríceps",         equipment: "Barra",         compound: false },
  { id: "t04", name: "Press francés con mancuernas",      muscle: "Tríceps",         equipment: "Mancuernas",    compound: false },
  { id: "t05", name: "Fondos en máquina / bancos",        muscle: "Tríceps",         equipment: "Máquina",       compound: false },
  { id: "t06", name: "Patada de tríceps",                 muscle: "Tríceps",         equipment: "Mancuernas",    compound: false },
  // ── Cuádriceps ────────────────────────────────────────────────────────────
  { id: "q01", name: "Sentadilla con barra",              muscle: "Cuádriceps",      equipment: "Barra",         compound: true  },
  { id: "q02", name: "Sentadilla Goblet",                 muscle: "Cuádriceps",      equipment: "Mancuernas",    compound: true  },
  { id: "q03", name: "Prensa de piernas (Leg Press)",     muscle: "Cuádriceps",      equipment: "Máquina",       compound: true  },
  { id: "q04", name: "Extensión de cuádriceps",           muscle: "Cuádriceps",      equipment: "Máquina",       compound: false },
  { id: "q05", name: "Zancadas (Lunges) con mancuernas",  muscle: "Cuádriceps",      equipment: "Mancuernas",    compound: true  },
  { id: "q06", name: "Step-up al banco",                  muscle: "Cuádriceps",      equipment: "Peso corporal", compound: true  },
  // ── Isquios / Glúteos ─────────────────────────────────────────────────────
  { id: "h01", name: "Peso muerto rumano con barra",      muscle: "Isquios/Glúteos", equipment: "Barra",         compound: true  },
  { id: "h02", name: "Peso muerto rumano con mancuernas", muscle: "Isquios/Glúteos", equipment: "Mancuernas",    compound: true  },
  { id: "h03", name: "Curl de isquiotibiales",            muscle: "Isquios/Glúteos", equipment: "Máquina",       compound: false },
  { id: "h04", name: "Hip Thrust con barra",              muscle: "Isquios/Glúteos", equipment: "Barra",         compound: true  },
  { id: "h05", name: "Patada de glúteo en polea",         muscle: "Isquios/Glúteos", equipment: "Polea",         compound: false },
  { id: "h06", name: "Buenos días (Good Mornings)",       muscle: "Isquios/Glúteos", equipment: "Barra",         compound: true  },
  // ── Gemelos ───────────────────────────────────────────────────────────────
  { id: "g01", name: "Elevación de talones de pie",       muscle: "Gemelos",         equipment: "Peso corporal", compound: false },
  { id: "g02", name: "Elevación de talones en máquina",   muscle: "Gemelos",         equipment: "Máquina",       compound: false },
  { id: "g03", name: "Elevación de talones en prensa",    muscle: "Gemelos",         equipment: "Máquina",       compound: false },
  // ── Core ──────────────────────────────────────────────────────────────────
  { id: "cr01", name: "Plancha abdominal (Plank)",        muscle: "Core",            equipment: "Peso corporal", compound: false },
  { id: "cr02", name: "Crunch en suelo",                  muscle: "Core",            equipment: "Peso corporal", compound: false },
  { id: "cr03", name: "Crunch en polea alta",             muscle: "Core",            equipment: "Polea",         compound: false },
  { id: "cr04", name: "Elevación de piernas colgado",     muscle: "Core",            equipment: "Peso corporal", compound: false },
  { id: "cr05", name: "Russian Twist",                    muscle: "Core",            equipment: "Peso corporal", compound: false },
  { id: "cr06", name: "Rueda abdominal (Ab Wheel)",       muscle: "Core",            equipment: "Accesorios",    compound: false },
  { id: "cr07", name: "Plancha lateral",                  muscle: "Core",            equipment: "Peso corporal", compound: false },
  // ── Full Body / Cardio ────────────────────────────────────────────────────
  { id: "fb01", name: "Peso muerto convencional",         muscle: "Full Body",       equipment: "Barra",         compound: true  },
  { id: "fb02", name: "Kettlebell Swing",                 muscle: "Full Body",       equipment: "Kettlebell",    compound: true  },
  { id: "fb03", name: "Burpees",                          muscle: "Full Body",       equipment: "Peso corporal", compound: true  },
  { id: "fb04", name: "Saltar la comba",                  muscle: "Cardio",          equipment: "Accesorios",    compound: false },
  { id: "fb05", name: "Bicicleta estática",               muscle: "Cardio",          equipment: "Máquina",       compound: false },
  { id: "fb06", name: "Cinta de correr",                  muscle: "Cardio",          equipment: "Máquina",       compound: false },
  { id: "fb07", name: "Remo (Rowing machine)",            muscle: "Cardio",          equipment: "Máquina",       compound: false },
];

const MUSCLE_GROUPS = ["Todos", ...new Set(EXERCISES_LIBRARY.map((e) => e.muscle))];
